### ISSUE TITLE
Windows 10 Building issues

### ISSUE THREAD

**Issue by EthereumEmperor** [bitcoin-ultimatum/orion#16]
Hey, @askiiRobotics & @dim4egster !
I would like to ask for assistance. I have tried to follow instructions on Windows build notes and gave it 3 tries before creating the issue.

First time I tried to perform the build on the newest Windows 10 build and v142 SDK. Went through the process step by step and checked everything twice in a row. I've got bn.h compiling errors, which means I couldn't build **ate-pairing** dependency for **libff**. I tried to work around it and prebuild it, but couldn't find a proper solution for msvc so I decided to get 1511 Windows Threshold 1 version (2016 Nov) which is 0x0A000001 version of SDK. It didn't work either. vcpkg manager kept giving CURL and ZLIB errors even though I put to ignore these versions. 
e.g. firstly I had to use link for the newer cmake on msvc, because internal is lower than 3.14. After that it said, that it find ZLIB, but version is ".." so I changed CURL cmake file to ignore zlib version, because it was 1.2.11 in the include files, so it should be correct work around and still it didn't work. Now it cannot generate links e.g.

```
 Target "btcu-qt" links to target "ZeroMQ::zmq" but the target was not
1>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
1>   an ALIAS target is missing?
```

I would like to ask you to update windows build notes and check it yourself, provide links for the required windows version downloads etc, thank you. I am sad, that I didn't ask for help earlier and wasted much time on trying different windows version in few tries. To sum it up: I've tried MSVC 2019 (v142), MSVC (v141) and tried to work around version cmake errors etc, even tried external cmake by linking the folders still didn't help.

**Comment by dim4egster** [comment]
Thank you for the issue! It's fixed for now!
